# Generated by Django 6.0 on 2025-12-18 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AirBNB_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.RemoveField(
            model_name='property',
            name='country',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
