# Generated by Django 6.0 on 2025-12-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirBNB_app', '0003_alter_booking_check_in_alter_booking_check_out_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], max_length=10),
        ),
    ]
